/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:dbc16a37-e19d-4e16-8cd0-5972353518eb",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_zWM5dnyy0",
    "aws_user_pools_web_client_id": "7tuncfe1514ndcqlrjluc80c4t",
    "oauth": {
        "domain": "amplifyparkingapp644543dd-644543dd-prod.auth.us-east-1.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "https://d1s5ugagn5woqa.cloudfront.net/auth/",
        "redirectSignOut": "https://d1s5ugagn5woqa.cloudfront.net/auth/signin/",
        //"redirectSignIn": "http//localhost:4200/auth/",
        //"redirectSignOut": "http://localhost:4200/auth/signin/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS",
    "aws_user_files_s3_bucket": "amplifyparkingapp393cba4924de48aab9a796b613fd26120306-prod",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
